-- MySQL Script generated by MySQL Workbench
-- Fri Jun  2 23:46:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quiz_web_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quiz_web_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quiz_web_app` DEFAULT CHARACTER SET utf8 ;
USE `quiz_web_app` ;

-- -----------------------------------------------------
-- Table `quiz_web_app`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz_web_app`.`user` (
  `id` INT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NULL,
  `email` VARCHAR(45) NULL,
  `password_hash` VARCHAR(128) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `is_anonymous` TINYINT NULL,
  `is_regular` TINYINT NULL,
  `is_admin` TINYINT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `quiz_web_app`.`quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz_web_app`.`quiz` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `active` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`title` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz_web_app`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz_web_app`.`question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quiz_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `answer_type` ENUM('multiple', 'single', 'essay') NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `quiz_id`),
  INDEX `fk_question_quiz1_idx` (`quiz_id` ASC) VISIBLE,
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE,
  CONSTRAINT `fk_question_quiz1`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `quiz_web_app`.`quiz` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz_web_app`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz_web_app`.`answer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question_id` INT NOT NULL,
  `question_quiz_id` INT NOT NULL,
  `answer` LONGTEXT NULL,
  PRIMARY KEY (`id`, `question_id`, `question_quiz_id`),
  INDEX `fk_answer_question1_idx` (`question_id` ASC, `question_quiz_id` ASC) VISIBLE,
  CONSTRAINT `fk_answer_question1`
    FOREIGN KEY (`question_id` , `question_quiz_id`)
    REFERENCES `quiz_web_app`.`question` (`id` , `quiz_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz_web_app`.`user_has_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz_web_app`.`user_has_answer` (
  `user_id` INT NOT NULL,
  `answer_id` INT NOT NULL,
  `answer_question_id` INT NOT NULL,
  `answer_question_quiz_id` INT NOT NULL,
  `essay` LONGTEXT NULL,
  PRIMARY KEY (`user_id`, `answer_id`, `answer_question_id`, `answer_question_quiz_id`),
  INDEX `fk_user_has_answer_answer1_idx` (`answer_id` ASC, `answer_question_id` ASC, `answer_question_quiz_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_answer_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `quiz_web_app`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_answer_answer1`
    FOREIGN KEY (`answer_id` , `answer_question_id` , `answer_question_quiz_id`)
    REFERENCES `quiz_web_app`.`answer` (`id` , `question_id` , `question_quiz_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `quiz_web_app`.`user_has_quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz_web_app`.`user_has_quiz` (
  `user_id` INT NOT NULL,
  `quiz_id` INT NOT NULL,
  `is_completed` TINYINT NULL,
  `approved` TINYINT NULL,
  `comment` LONGTEXT NULL,
  PRIMARY KEY (`user_id`, `quiz_id`),
  INDEX `fk_user_has_quiz_quiz1_idx` (`quiz_id` ASC) VISIBLE,
  INDEX `fk_user_has_quiz_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_quiz_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `quiz_web_app`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_quiz_quiz1`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `quiz_web_app`.`quiz` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `quiz_web_app`.`user_has_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz_web_app`.`user_has_question` (
  `user_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `question_quiz_id` INT NOT NULL,
  `is_answered` TINYINT NULL,
  `approved` TINYINT NULL,
  `comment` LONGTEXT NULL,
  PRIMARY KEY (`user_id`, `question_id`, `question_quiz_id`),
  INDEX `fk_user_has_question_question1_idx` (`question_id` ASC, `question_quiz_id` ASC) VISIBLE,
  INDEX `fk_user_has_question_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_question_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `quiz_web_app`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_question_question1`
    FOREIGN KEY (`question_id` , `question_quiz_id`)
    REFERENCES `quiz_web_app`.`question` (`id` , `quiz_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
